### ISSUE TITLE
[Feature Request] Initialize Avatar Editor with character .glb link / Partial customization

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [readyplayerme/rpm-unreal-webview#2]
I believe this issue might actually be two, but here goes.

Are there plans to support the initialization of the avatar editor with an already existing character? As if updating an existing character. For example, adding the field `Init glb URL` in `RpmWebViewWidget`, allows users/developers to specify an existing character (with a valid URL) and use it as the basis for the avatar editor.

Assuming the existence of the previous feature, my second question is if there are partial editing capabilities. For example, allowing the changing of the outfit but not of the head.

**Comment by gadamyan** [comment]
The Webview doesn't have the capability of editing the previously created avatar, I don't think there are plans for supporting it. You can send a feature request to the customer support team if you want.
In theory, you can achieve this by using the custom avatar creator(Alpha). It has an AvatarId field, but it only can be used by the owner of the avatar.
For the second question, in theory, you can achieve what you want by modifying the custom avatar creator UI blueprints. But afterwards you would need to apply manual changes if you decide to update the your version with the new changes.
